version: '3.4'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  catalogue:
    image: catalogue
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
